### ISSUE TITLE
LEDscroll_project

### ISSUE THREAD

**Issue by jyotimc** [DerellLicht/LedScroll#1]
I am unable to build this

**Comment by DerellLicht** [comment]
Interesting... I couldn't either.  Pull the commit that I just pushed, which fixes the Makefile.  I can build it now.

What build environment are you using?  I use MinGW 4.4.1
I haven't tried building with Visual Studio; it *should* work, but I don't know.

**Comment by jyotimc** [comment]
I am using Visual Studio.

**Comment by DerellLicht** [comment]
Well, perhaps you could tell me *what* doesn't build??  Your original post wasn't very informative.

**Comment by DerellLicht** [comment]
Okay, I have this building with Visual Studio 2010 now, but need to do some tweaking of the configuration, in order for it to work properly with the default fntcol directory.  I'll work on that tonight, then get a new build committed.

**Comment by DerellLicht** [comment]
Current commit now builds with Visual Studio 2010.  Note that in order to get the executable to run properly, the fntcol font collection will need to be located in ..\fntcol relative to the location of LedScroll.exe, which is located in ./LedScroll/LedScroll/Debug in this build.

**Comment by jyotimc** [comment]
I am not finding VC++ file in this project so as to build in visual studio.Instead i find .exe which says its not a trustworthy file to execute in visual studio.

**Comment by jyotimc** [comment]
In this link http://www.derelllicht.com/LedScroll.html I could find visual
studio file  for font viewer but not for led scrolling demo.

**Comment by DerellLicht** [comment]
The Visual Studio 2010 build file is in .\LedScroll\LedScroll.sln
It will build the executable in .\LedScroll\Debug\LedScroll.exe
However, for the program to run as expected, you have to obtain the font files as well.
These are available at https://github.com/DerellLicht/fntcol.git
For the default paths to work, you have to place the fntcol directory at ..\fntcol, relative to the location of LedScroll.exe; so this would be .\LedScroll\fntcol
All of this is documented in the readme.txt file now.

**Comment by DerellLicht** [comment]
BTW, if your antivirus program reports the .exe as having a virus, it is a false positive, you should report it to the antivirus company.  this program was built with the source code that you see; it definitely does not have a virus in it.

**Comment by jyotimc** [comment]
In this project link  http://www.derelllicht.com/LedScroll.html I can see
the two demo files .main dialog and font viewer dialog. But on execution I
get font viewer demo file but not the first one.

**Comment by DerellLicht** [comment]
Do you mean that you get a dialog with just a "font viewer" button?
If so, that's because you don't have the font files located in ../fntcol, as I instructed above.
I'll admit that the website isn't really documented completely, unfortunately.

**Comment by DerellLicht** [comment]
Okay, I've modified the zip file on my website, so the font files are where they need to be.
It should run properly for you now, without having to think about what's going on.

Mind you, if you actually build the program with Visual Studio and try to run it, you will need to read and follow the instructions that I've been giving you.  For now, though, the website distribution file works properly.

**Comment by jyotimc** [comment]
See the attached file .On execution i get that dialog, in which i can load
different fonts.

**Comment by jyotimc** [comment]
See this attached file. I am not able to look exactly for this demo dialog
box on execution of LED_scroll visual studio file, where it displays time.

**Comment by DerellLicht** [comment]
Unfortunately, I don't see any attachments. ??
